version: '3.8'

services:
  web-dev:
    build: .
    container_name: chatapp-dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/chatapp_dev/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat_db

volumes:
    postgres_data_dev: